### ISSUE TITLE
Suggestion to refact

### ISSUE THREAD

**Issue by RaphaelOliveiraMoura** [jopcmelo/gostack-gympoint#6]
Hello,
I saw in your app that one student can to has just one enrolment okay?

So, my suggestion is create your enrolments table in database with field `student_id` with prop unique. Make sense?

I see that you already make a validation in your controller to don't save two students there, but adding unique attribute in the column, you add one more level of validation to your application.

What do you think about this?

I opened a pull request with the changes in the code. #5

**Comment by jopcmelo** [comment]
Nice, Raphael!!

I've really went unnoticed about that.

I'm going to merge your pull request right now. Thank you so much!
